
include  ../tools/Makefile.base-vars

all:
	

SRC = docstyles.css 

$(INSTALL_SUBDIR):
	$(MKDIR) $(INSTALL_SUBDIR)

#install
install: $(INSTALL_SUBDIR)
	$(INSTALL_DATA) $(SRC) $(INSTALL_SUBDIR)

clean:
	

