=begin pod

=CHAPTER Предисловие 

Perl 6 представляет собой спецификацию, для которой существует несколько реализаций в виде компиляторов и интерпретаторов, каждая из которых находится на разной степени завершенности. Все эти реализации являются основной движущей силой развития языка, указывая на слабые стороны и противоречия в дизайне Perl 6. С их помощью обнаруживается функционал, сложный в реализации и недостаточно важный. Благодаря своего рода "естественному отбору" среди реализаций происходит процесс эволюции, который улучшает связанность и целостность спецификации языка Perl 6.


Perl 6 универсален, интуитивен и гибок. Он охватывает несколько парадигм таких как процедурное, объектно-ориентированное и функциональное программирование, а также предлагает мощные инструменты для обработки текста.


=head1 Perl должен оставаться Perl

Perl 6 по прежнему остается Perl. Что это означает ? Конечно же это не значит, что Perl 6 обладает такой же функциональностью или синтаксически совместим с Perl 5. В таком случае это была бы очередная версия Perl 5.

Perl является философией и оба языка, Perl 5 и Perl 6, разделяют ее. Согласно этой философии существует больше одного способа достичь результата , а также простые вещи должны оставаться простыми, а сложные - возможными. 
Эти принципы связаны с прошлым, настоящим и будущим Perl и определяют фундаментальное предназначение Perl 6. В Perl 6 легкие вещи стали более легкими, а трудные - более возможными.


=head1 Реализации Perl 6 

Являясь спецификацией, Perl 6 подразумевает неограниченное количество реализаций. Любая из реализаций, успешно проходящая тесты, может назвать себя "Perl 6". Примеры, приведенные в книге, могут быть выполнены как с помощью компилятора I<Rakudo Perl 6> I<(наиболее развитой на момент написания книги)>, так и любой другой.

=head1 Установка Rakudo и запуск программ

Подробные инструкции по установке Rakudo доступны по адресу L<http://www.rakudo.org/how-to-get-rakudo>. Доступны как исходные тексты для сборки, так и уже предварительно скомпилированный пакет для Windows: L<http://sourceforge.net/projects/parrotwin32/files/>.

Если вы являетесь пользователем FreeBSD, то для установки достаточно выполнить команду:

=output
    pkg_add -r rakudB<o>

Проверить правильность установки Rakudo можно с помощью команды:

=output
 perl6 -e 'say "Hello world!"'

В случае неудачи, проверьте наличие пути для запуска perl6 в переменной C<PATH>.
Есть так же переменная C<PERL6LIB>, с помощью которой можно использовать дополнительные модули для Perl 6. Для этого необходимо указать пути к ним в вашей системе аналогично C<PERL5LIB> для Perl 5.

=head1 Дополнительные источники информации

Если вы хотите принять участие в развитии языка Perl 6, поделится своим опытом воспользуйтесь следующими ресурсами:

=for item :term('World Wide Web')
Отправной точкой ресурсов, посвященных Perl 6, является домашняя страница языка : C<http://perl6.org/>.

=for item :term<IRC>
Задать вопросы о Perl 6 можно на канале C<#perl6> по адресу C<irc.freenode.net>.

=for item :term('Списоки рассылки')
Для получения помощи о Perl 6 достаточно отправить письмо по адресу
C<perl6-users@perl.org>.
По вопросам относящимся к спецификации Perl 6 или компиляторам можно обратиться по следующим адресам соответственно: C<perl6-language@perl.org>, C<perl6-compiler@perl.org>.

=end pod
