#*************************
# VARIABLES
#*************************
include ../tools/Makefile.base-vars

NAME = book
OUTNAME = ru-perl6-book
DIR = book
#FO_XSL= fo.book-stylesheet.xsl
#include  ../tools/Makefile.base

all:
	${MAKE} install INSTALL_SUBDIR=../latest_build

include ../tools/Makefile.base-rules

IMAGES = img
